export const FETCH_USER_SEARCH_DATA_REQUEST = 'FETCH_USER_SEARCH_DATA_REQUEST';
export const FETCH_USER_SEARCH_DATA_SUCCESS = 'FETCH_USER_SEARCH_DATA_SUCCESS';
export const FETCH_USER_SEARCH_DATA_FAIL = 'FETCH_USER_SEARCH_DATA_FAIL';
export const FETCH_USER_SEARCH_DATA_RESET = 'FETCH_USER_SEARCH_DATA_RESET';

export const FETCH_AGE_DATA_REQUEST = 'FETCH_AGE_DATA_REQUEST';
export const FETCH_AGE_DATA_SUCCESS = 'FETCH_AGE_DATA_SUCCESS';
export const FETCH_AGE_DATA_FAIL = 'FETCH_AGE_DATA_FAIL';
